spring:
  datasource:
    url: jdbc:mysql://us-cdbr-iron-east-01.cleardb.net/heroku_4cc5f4d6131b075?reconnect=true&characterEncoding=utf8&useUnicode=true
    username: bc91784b965748
    password: 80fd2b5f
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      test-while-idle: false
      validation-query: SELECT 1
    initialization-mode: never
    platform: mysql
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000

check-user-scopes: true

server:
  port: 9092